name: CI to staging

on:
  push:
    branches: 
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy to staging
      env:
        VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
    - uses: teamnovu/vapor-action@master
      with:
        args: deploy staging 
